Fix error C3848: expression having type 'const VCSStatusItemCmp' would lose some const-volatile qualifiers in order to call 'bool VCSStatusItemCmp::operator ()(const VCSStatusItem &,const VCSStatusItem &)' in Visual Studio 2019
The operator() used for comparison in sorting algorithm need to be declared const in standard C++